const products = [
  {
    Id: 1,
    City: "Bengaluru",
    Category: "TV",
    Brand: "Samsung",
    Name: "Samsung LED",
    Type: "LED",
    Size: "32 inches",
    Price: 33500.5,
    Stock: 17,
  },
  {
    Id: 2,
    City: "Bengaluru",
    Category: "TV",
    Brand: "Samsung",
    Name: "Samsung LED",
    Type: "LED",
    Size: "42 inches",
    Price: 41850,
    Stock: 9,
  },
  {
    Id: 3,
    City: "Mumbai",
    Category: "TV",
    Brand: "Samsung",
    Name: "Samsung LED",
    Type: "LED",
    Size: "32 inches",
    Price: 33500,
    Stock: 29,
  },
  {
    Id: 4,
    City: "Bengaluru",
    Category: "Mobile",
    Brand: "Samsung",
    Name: "Samsung S8",
    Type: "Super Amoled",
    Size: "6 inches",
    Price: 30900.5,
    Stock: 35,
  },
  {
    Id: 5,
    City: "Mumbai",
    Category: "Mobile",
    Brand: "Samsung",
    Name: "Samsung S8",
    Type: "Super Amoled",
    Size: "6 inches",
    Price: 29980,
    Stock: 48,
  },
  {
    Id: 6,
    City: "Bengaluru",
    Category: "Microwave",
    Brand: "Samsung",
    Name: "Samsung 32 L Convection",
    Type: "Convection",
    Size: "32 litres",
    Price: 19500.5,
    Stock: 22,
  },
  {
    Id: 7,
    City: "Mumbai",
    Category: "Microwave",
    Brand: "Samsung",
    Name: "Samsung 32 L Convection",
    Type: "Convection",
    Size: "32 litres",
    Price: 19600.5,
    Stock: 21,
  },
  {
    Id: 8,
    City: "Delhi",
    Category: "Microwave",
    Brand: "Samsung",
    Name: "Samsung 32 L Convection",
    Type: "Convection",
    Size: "32 litres",
    Price: 18990.5,
    Stock: 23,
  },
  {
    Id: 9,
    City: "Bengaluru",
    Category: "TV",
    Brand: "LG",
    Name: "LG LED",
    Type: "LED",
    Size: "32 inches",
    Price: 31600,
    Stock: 21,
  },
  {
    Id: 10,
    City: "Mumbai",
    Category: "TV",
    Brand: "LG",
    Name: "LG LED",
    Type: "LED",
    Size: "32 inches",
    Price: 30650,
    Stock: 33,
  },
  {
    Id: 11,
    City: "Bengaluru",
    Category: "TV",
    Brand: "LG",
    Name: "LG LED",
    Type: "LED",
    Size: "50 inches",
    Price: 51780.5,
    Stock: 15,
  },
  {
    Id: 12,
    City: "Mumbai",
    Category: "TV",
    Brand: "LG",
    Name: "LG LED",
    Type: "LED",
    Size: "50 inches",
    Price: 50800,
    Stock: 35,
  },
  {
    Id: 13,
    City: "Bengaluru",
    Category: "Mobile",
    Brand: "LG",
    Name: "LG V30+",
    Type: "OLED",
    Size: "6 inches",
    Price: 44990.5,
    Stock: 16,
  },
  {
    Id: 14,
    City: "Mumbai",
    Category: "Mobile",
    Brand: "LG",
    Name: "LG V30+",
    Type: "OLED",
    Size: "6 inches",
    Price: 43100.5,
    Stock: 17,
  },
  {
    Id: 15,
    City: "Bengaluru",
    Category: "Microwave",
    Brand: "LG",
    Name: "LG 32 L Convection",
    Type: "Convection",
    Size: "32 litres",
    Price: 26990,
    Stock: 16,
  },
  {
    Id: 16,
    City: "Mumbai",
    Category: "Microwave",
    Brand: "LG",
    Name: "LG 32 L Convection",
    Type: "Convection",
    Size: "32 litres",
    Price: 26450,
    Stock: 20,
  },
  {
    Id: 17,
    City: "Delhi",
    Category: "Microwave",
    Brand: "LG",
    Name: "LG 32 L Convection",
    Type: "Convection",
    Size: "32 litres",
    Price: 25700.5,
    Stock: 28,
  },
  {
    Id: 18,
    City: "Bengaluru",
    Category: "Mobile",
    Brand: "Nokia",
    Name: "Nokia 8",
    Type: "IPS QHD",
    Size: "5.3 inches",
    Price: 27718,
    Stock: 17,
  },
  {
    Id: 19,
    City: "Mumbai",
    Category: "Mobile",
    Brand: "Nokia",
    Name: "Nokia 8",
    Type: "IPS QHD",
    Size: "5.3 inches",
    Price: 26870.5,
    Stock: 20,
  },
  {
    Id: 20,
    City: "Delhi",
    Category: "Mobile",
    Brand: "Nokia",
    Name: "Nokia 8",
    Type: "IPS QHD",
    Size: "5.3 inches",
    Price: 26350,
    Stock: 22,
  },
  {
    Id: 21,
    City: "Bengaluru",
    Category: "Mobile",
    Brand: "Sony",
    Name: "Sony Xperia XA2 Ultra",
    Type: "OLED",
    Size: "5.5 inches",
    Price: 49000,
    Stock: 20,
  },
  {
    Id: 22,
    City: "Mumbai",
    Category: "Mobile",
    Brand: "Sony",
    Name: "Sony Xperia XA2 Ultra",
    Type: "OLED",
    Size: "5.5 inches",
    Price: 48650.5,
    Stock: 22,
  },
  {
    Id: 23,
    City: "Delhi",
    Category: "Mobile",
    Brand: "Sony",
    Name: "Sony Xperia XA2 Ultra",
    Type: "OLED",
    Size: "5.5 inches",
    Price: 48150.5,
    Stock: 18,
  },
  {
    Id: 24,
    City: "Bengaluru",
    Category: "TV",
    Brand: "Sony",
    Name: "Sony Bravia LED",
    Type: "LED",
    Size: "32 inches",
    Price: 35870.5,
    Stock: 25,
  },
  {
    Id: 25,
    City: "Mumbai",
    Category: "TV",
    Brand: "Sony",
    Name: "Sony Bravia LED",
    Type: "LED",
    Size: "32 inches",
    Price: 35550,
    Stock: 30,
  },
  {
    Id: 26,
    City: "Delhi",
    Category: "TV",
    Brand: "Sony",
    Name: "Sony Bravia LED",
    Type: "LED",
    Size: "32 inches",
    Price: 34990,
    Stock: 34,
  },
  {
    Id: 27,
    City: "Bengaluru",
    Category: "TV",
    Brand: "Sony",
    Name: "Sony Bravia LED",
    Type: "LED",
    Size: "40 inches",
    Price: 46660.5,
    Stock: 17,
  },
  {
    Id: 28,
    City: "Mumbai",
    Category: "TV",
    Brand: "Sony",
    Name: "Sony Bravia LED",
    Type: "LED",
    Size: "40 inches",
    Price: 45570.5,
    Stock: 16,
  },
  {
    Id: 29,
    City: "Delhi",
    Category: "TV",
    Brand: "Sony",
    Name: "Sony Bravia LED",
    Type: "LED",
    Size: "40 inches",
    Price: 45990,
    Stock: 21,
  },
  {
    Id: 30,
    City: "Bengaluru",
    Category: "TV",
    Brand: "Onida",
    Name: "Onida LED",
    Type: "LED",
    Size: "43 inches",
    Price: 30990,
    Stock: 20,
  },
  {
    Id: 31,
    City: "Mumbai",
    Category: "TV",
    Brand: "Onida",
    Name: "Onida LED",
    Type: "LED",
    Size: "43 inches",
    Price: 30990,
    Stock: 18,
  },
  {
    Id: 32,
    City: "Delhi",
    Category: "TV",
    Brand: "Onida",
    Name: "Onida LED",
    Type: "LED",
    Size: "43 inches",
    Price: 30650,
    Stock: 26,
  },
  {
    Id: 33,
    City: "Bengaluru",
    Category: "Microwave",
    Brand: "Onida",
    Name: "Onida 28 L Convection",
    Type: "Convection",
    Size: "28 litres",
    Price: 13990,
    Stock: 26,
  },
  {
    Id: 34,
    City: "Mumbai",
    Category: "Microwave",
    Brand: "Onida",
    Name: "Onida 28 L Convection",
    Type: "Convection",
    Size: "28 litres",
    Price: 13650,
    Stock: 24,
  },
  {
    Id: 35,
    City: "Delhi",
    Category: "Microwave",
    Brand: "Onida",
    Name: "Onida 28 L Convection",
    Type: "Convection",
    Size: "28 litres",
    Price: 13650,
    Stock: 32,
  },
  {
    Id: 36,
    City: "Bengaluru",
    Category: "Shoe",
    Brand: "Bata India",
    Name: "Bata India",
    Type: "Casual",
    Size: "7 inches",
    Price: 4721,
    Stock: 17,
  },
  {
    Id: 37,
    City: "Bengaluru",
    Category: "Shoe",
    Brand: "Relaxo Footwear",
    Name: "Relaxo Footwear",
    Type: "Casual",
    Size: "7.5 inches",
    Price: 5622,
    Stock: 77,
  },
  {
    Id: 38,
    City: "Bengaluru",
    Category: "Shoe",
    Brand: "Mirza Intl",
    Name: "Mirza Intl",
    Type: "Casual",
    Size: "8 inches",
    Price: 3655,
    Stock: 29,
  },
  {
    Id: 39,
    City: "Bengaluru",
    Category: "Shoe",
    Brand: "Superhouse",
    Name: "Superhouse",
    Type: "Sports",
    Size: "8 inches",
    Price: 17854,
    Stock: 35,
  },
  {
    Id: 40,
    City: "Bengaluru",
    Category: "Shoe",
    Brand: "Liberty Shoes",
    Name: "Liberty Shoes",
    Type: "Sports",
    Size: "8.5 inches",
    Price: 14711,
    Stock: 48,
  },
  {
    Id: 41,
    City: "Bengaluru",
    Category: "Shoe",
    Brand: "Nike International",
    Name: "Nike International",
    Type: "Sports",
    Size: "9 inches",
    Price: 11987,
    Stock: 22,
  },
  {
    Id: 42,
    City: "Bengaluru",
    Category: "Bag",
    Brand: "Super Tannery",
    Name: "Super Tannery",
    Type: "Backpack",
    Size: "10 litres",
    Price: 4140,
    Stock: 21,
  },
  {
    Id: 43,
    City: "Bengaluru",
    Category: "Bag",
    Brand: "Sreeleathers",
    Name: "Sreeleathers",
    Type: "Backpack",
    Size: "22 litres",
    Price: 5140,
    Stock: 23,
  },
  {
    Id: 44,
    City: "Bengaluru",
    Category: "Bag",
    Brand: "Lawreshwar Poly",
    Name: "Lawreshwar Poly",
    Type: "Backpack",
    Size: "12 litres",
    Price: 4999,
    Stock: 21,
  },
  {
    Id: 45,
    City: "Bengaluru",
    Category: "Bag",
    Brand: "Tinna Rubber an",
    Name: "Tinna Rubber an",
    Type: "Backpack",
    Size: "15 litres",
    Price: 5700,
    Stock: 33,
  },
  {
    Id: 46,
    City: "Bengaluru",
    Category: "Bag",
    Brand: "Sarup Ind",
    Name: "Sarup Ind",
    Type: "Sports",
    Size: "17 litres",
    Price: 6400,
    Stock: 39,
  },
  {
    Id: 47,
    City: "Bengaluru",
    Category: "Bag",
    Brand: "Phoenix Intl",
    Name: "Phoenix Intl",
    Type: "Sports",
    Size: "18 litres",
    Price: 7470,
    Stock: 35,
  },
  {
    Id: 48,
    City: "Bengaluru",
    Category: "Bag",
    Brand: "Mayur Leather",
    Name: "Mayur Leather",
    Type: "Sports",
    Size: "16 litres",
    Price: 5510,
    Stock: 22,
  },
  {
    Id: 49,
    City: "Mumbai",
    Category: "Shoe",
    Brand: "Bata India",
    Name: "Bata India",
    Type: "Casual",
    Size: "7 inches",
    Price: 4644,
    Stock: 55,
  },
  {
    Id: 50,
    City: "Mumbai",
    Category: "Shoe",
    Brand: "Relaxo Footwear",
    Name: "Relaxo Footwear",
    Type: "Casual",
    Size: "7.5 inches",
    Price: 5600,
    Stock: 44,
  },
  {
    Id: 51,
    City: "Mumbai",
    Category: "Shoe",
    Brand: "Mirza Intl",
    Name: "Mirza Intl",
    Type: "Casual",
    Size: "8 inches",
    Price: 3510,
    Stock: 32,
  },
  {
    Id: 52,
    City: "Mumbai",
    Category: "Shoe",
    Brand: "Superhouse",
    Name: "Superhouse",
    Type: "Sports",
    Size: "8 inches",
    Price: 16540,
    Stock: 60,
  },
  {
    Id: 53,
    City: "Mumbai",
    Category: "Shoe",
    Brand: "Liberty Shoes",
    Name: "Liberty Shoes",
    Type: "Sports",
    Size: "8.5 inches",
    Price: 12810,
    Stock: 50,
  },
  {
    Id: 54,
    City: "Mumbai",
    Category: "Shoe",
    Brand: "Nike International",
    Name: "Nike International",
    Type: "Sports",
    Size: "9 inches",
    Price: 12870,
    Stock: 71,
  },
  {
    Id: 55,
    City: "Mumbai",
    Category: "Bag",
    Brand: "Super Tannery",
    Name: "Super Tannery",
    Type: "Backpack",
    Size: "10 litres",
    Price: 4200,
    Stock: 52,
  },
  {
    Id: 56,
    City: "Mumbai",
    Category: "Bag",
    Brand: "Sreeleathers",
    Name: "Sreeleathers",
    Type: "Backpack",
    Size: "19 litres",
    Price: 5150,
    Stock: 20,
  },
  {
    Id: 57,
    City: "Mumbai",
    Category: "Bag",
    Brand: "Lawreshwar Poly",
    Name: "Lawreshwar Poly",
    Type: "Backpack",
    Size: "12 litres",
    Price: 5050,
    Stock: 64,
  },
  {
    Id: 58,
    City: "Mumbai",
    Category: "Bag",
    Brand: "Tinna Rubber an",
    Name: "Tinna Rubber an",
    Type: "Backpack",
    Size: "15 litres",
    Price: 5850,
    Stock: 62,
  },
  {
    Id: 59,
    City: "Mumbai",
    Category: "Bag",
    Brand: "Sarup Ind",
    Name: "Sarup Ind",
    Type: "Sports",
    Size: "17 litres",
    Price: 6410.5,
    Stock: 35,
  },
  {
    Id: 60,
    City: "Mumbai",
    Category: "Bag",
    Brand: "Phoenix Intl",
    Name: "Phoenix Intl",
    Type: "Sports",
    Size: "18 litres",
    Price: 7340.5,
    Stock: 40,
  },
  {
    Id: 61,
    City: "Mumbai",
    Category: "Bag",
    Brand: "Mayur Leather",
    Name: "Mayur Leather",
    Type: "Sports",
    Size: "16 litres",
    Price: 5460,
    Stock: 47,
  },
  {
    Id: 62,
    City: "Delhi",
    Category: "Shoe",
    Brand: "Bata India",
    Name: "Bata India",
    Type: "Casual",
    Size: "7 inches",
    Price: 4422,
    Stock: 66,
  },
  {
    Id: 63,
    City: "Delhi",
    Category: "Shoe",
    Brand: "Relaxo Footwear",
    Name: "Relaxo Footwear",
    Type: "Casual",
    Size: "7.5 inches",
    Price: 5150,
    Stock: 81,
  },
  {
    Id: 64,
    City: "Delhi",
    Category: "Shoe",
    Brand: "Mirza Intl",
    Name: "Mirza Intl",
    Type: "Casual",
    Size: "8 inches",
    Price: 3780,
    Stock: 41,
  },
  {
    Id: 65,
    City: "Delhi",
    Category: "Shoe",
    Brand: "Superhouse",
    Name: "Superhouse",
    Type: "Sports",
    Size: "8 inches",
    Price: 16600,
    Stock: 24,
  },
  {
    Id: 66,
    City: "Delhi",
    Category: "Shoe",
    Brand: "Liberty Shoes",
    Name: "Liberty Shoes",
    Type: "Sports",
    Size: "8.5 inches",
    Price: 14200,
    Stock: 44,
  },
  {
    Id: 67,
    City: "Delhi",
    Category: "Shoe",
    Brand: "Nike International",
    Name: "Nike International",
    Type: "Sports",
    Size: "9 inches",
    Price: 11980,
    Stock: 66,
  },
  {
    Id: 68,
    City: "Delhi",
    Category: "Bag",
    Brand: "Super Tannery",
    Name: "Super Tannery",
    Type: "Backpack",
    Size: "10 litres",
    Price: 4050,
    Stock: 26,
  },
  {
    Id: 69,
    City: "Delhi",
    Category: "Bag",
    Brand: "Sreeleathers",
    Name: "Sreeleathers",
    Type: "Backpack",
    Size: "25 litres",
    Price: 5150.5,
    Stock: 24,
  },
  {
    Id: 70,
    City: "Delhi",
    Category: "Bag",
    Brand: "Lawreshwar Poly",
    Name: "Lawreshwar Poly",
    Type: "Backpack",
    Size: "12 litres",
    Price: 4899,
    Stock: 32,
  },
  {
    Id: 71,
    City: "Delhi",
    Category: "Bag",
    Brand: "Tinna Rubber an",
    Name: "Tinna Rubber an",
    Type: "Backpack",
    Size: "15 litres",
    Price: 5600,
    Stock: 35,
  },
  {
    Id: 72,
    City: "Delhi",
    Category: "Bag",
    Brand: "Sarup Ind",
    Name: "Sarup Ind",
    Type: "Sports",
    Size: "17 litres",
    Price: 6380,
    Stock: 37,
  },
  {
    Id: 73,
    City: "Delhi",
    Category: "Bag",
    Brand: "Phoenix Intl",
    Name: "Phoenix Intl",
    Type: "Sports",
    Size: "18 litres",
    Price: 7500,
    Stock: 74,
  },
  {
    Id: 74,
    City: "Delhi",
    Category: "Bag",
    Brand: "Mayur Leather",
    Name: "Mayur Leather",
    Type: "Sports",
    Size: "16 litres",
    Price: 5680,
    Stock: 46,
  },
];

export default products;
